# -*- coding: utf-8 -*-
"""Traffic _Simulation_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nE1ocasQVyZgNEjq8y4czhtAIxpmw93v
"""
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

class TrafficDataSimulator:
    def __init__(self, num_samples=1000):
        self.num_samples = num_samples

    def generate_data(self):
        vehicle_count = np.random.randint(30, 200, size=self.num_samples)
        speed = np.random.randint(30, 100, size=self.num_samples)
        time_of_day = np.random.randint(0, 24, size=self.num_samples)
        congestion_level = self._generate_congestion_level(vehicle_count, speed, time_of_day)
        return vehicle_count, speed, time_of_day, congestion_level

    def _generate_congestion_level(self, vehicle_count, speed, time_of_day):
        congestion_level = []
        for i in range(len(vehicle_count)):
            if 7 <= time_of_day[i] <= 9:
                if vehicle_count[i] > 100 and speed[i] < 50:
                    congestion_level.append(2)
                elif vehicle_count[i] > 50 and speed[i] < 70:
                    congestion_level.append(1)
                else:
                    congestion_level.append(0)
            elif 17 <= time_of_day[i] <= 19:
                if vehicle_count[i] > 80 and speed[i] < 60:
                    congestion_level.append(2)
                elif vehicle_count[i] > 40 and speed[i] < 80:
                    congestion_level.append(1)
                else:
                    congestion_level.append(0)
            else:
                if vehicle_count[i] > 100 and speed[i] < 50:
                    congestion_level.append(2)
                elif vehicle_count[i] > 50 and speed[i] < 70:
                    congestion_level.append(1)
                else:
                    congestion_level.append(0)
        return np.array(congestion_level)

class TrafficDataVisualizer:
    def __init__(self, vehicle_count, speed, congestion_level):
        self.vehicle_count = vehicle_count
        self.speed = speed
        self.congestion_level = congestion_level

    def plot_data(self):
        plt.figure(figsize=(10, 6))
        congestion_counts = [np.sum(self.congestion_level == level) for level in np.unique(self.congestion_level)]
        plt.bar(np.unique(self.congestion_level), congestion_counts, color=['green', 'orange', 'red'])
        plt.title("Traffic Congestion Level Distribution")
        plt.xlabel("Congestion Level")
        plt.ylabel("Frequency")
        plt.xticks([0, 1, 2], ["Low", "Medium", "High"])
        plt.show()

class TrafficCongestionPredictor:
    def __init__(self):
        self.model = LogisticRegression(max_iter=1000)

    def train_model(self, vehicle_count, speed, time_of_day, congestion_level):
        X = np.column_stack((vehicle_count, speed, time_of_day))
        y = congestion_level
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
        self.model.fit(X_train, y_train)
        y_pred = self.model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        print(f"Model Accuracy: {accuracy * 100:.2f}%")

    def predict_congestion(self, vehicle_count, speed, time_of_day):
        return self.model.predict(np.array([[vehicle_count, speed, time_of_day]]))[0]

def main():
    simulator = TrafficDataSimulator(num_samples=1000)
    vehicle_count, speed, time_of_day, congestion_level = simulator.generate_data()

    visualizer = TrafficDataVisualizer(vehicle_count, speed, congestion_level)
    visualizer.plot_data()

    predictor = TrafficCongestionPredictor()
    predictor.train_model(vehicle_count, speed, time_of_day, congestion_level)

    try:
        test_vehicle_count = int(input("Enter number of vehicles: "))
        test_speed = int(input("Enter vehicle speed (km/h): "))
        test_time_of_day = int(input("Enter time of day (0-23): "))

        if not (0 <= test_time_of_day <= 23):
            raise ValueError("Time of day must be between 0 and 23.")

        predicted_congestion = predictor.predict_congestion(test_vehicle_count, test_speed, test_time_of_day)
        print(f"Predicted Congestion for {test_vehicle_count} vehicles, {test_speed} km/h speed, and {test_time_of_day} hour: {predicted_congestion}")

    except ValueError as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()
